### ISSUE TITLE
Add third party billing to the client model

### ISSUE THREAD

**Issue by maximest-pierre** [savoirfairelinux/santropol-feast#110]

**Comment by lamontfr** [comment]
This is in the contributor column on the Waffle. I would like to know what is the requirement, so I can understand the work to be done. Please give more info. I will also post this question in the mailing list.

**Comment by RignonNoel** [comment]
Actually ```billing_address``` and ```facturation``` fields are in the Clients class of the member/models.py.

We want authorize a third party to pay for the client (children, government, etc..). So we need to upgrade the model to externalize this fields.

---

A solution can be:

1. Create a new class of model named ```Billing``` (or other name, i'm not the best in english)
2. Add fields ```first name```, ```last name```, ```address``` and ```facturation_type``` in ```Billing``` class
3. Delete the two fields ```biling_address``` and ```facturation``` in ```Client``` class
4. Add a foreign key in ```Client``` to ```Biling```


With this solution, a third party can pay for the client. And we can store multiple biling information in the time to keep a history of the client or just to change easily in the future.

**Comment by lamontfr** [comment]
Hi Noel,
I propose the solution shown in the 2 attached files (see below). Here is a summary of the main changes (relations are temporarily marked v0,2 to highlight changes).
- Added Payer Class (see details in ...-uml.txt) which points to Client and to Address. This class keeps the current billing agreement and also the past history. I translated "facturation" as "invoicing".
- Moved some attributes from Client to Payer
- Member now points to Address (because in the current data model, a member can have many addresses at the same time, how do we know which one to use ?)

I have a few questions.
- How can I get this issue 110 assigned to me ?
- We could simplify the diagram if a Payer can be a special case of Member. For this I would like to talk to a "domain expert" to understand their real world stories, may be at Santropol Roulant ?

We could also discuss it in person or on the phone. Let me know. Regards,
- Francois.

[future_data_model_uml.txt](https://github.com/savoirfairelinux/santropol-feast/files/265279/future_data_model_uml.txt)
![future_data_model](https://cloud.githubusercontent.com/assets/8512608/15276903/ff4801a6-1ac2-11e6-9450-a58a8b4e8f5a.png)

**Comment by RignonNoel** [comment]
We need to see that with @manumilou. It's the mentor in Savoir Faire Linux who work in the older software of Santropol.

---

> the current billing agreement and also the past history. I translated "facturation" as "invoicing".

The translation of the class need to be a different issue. But personally i'm ok with that.

> Member now points to Address (because in the current data model, a member can have many
> addresses at the same time, how do we know which one to use ?)

Idem, we need an other issue to discuss this point. It's more complicated.

**Comment by lamontfr** [comment]
Here is an improvement (I think).

![future_data_model_02a](https://cloud.githubusercontent.com/assets/8512608/15393507/bf3ea908-1d9b-11e6-9221-df91269c16dd.png)

This would need a validation rule to the effect that "An active Paid_by instance must exist for a Client (such that we can bill him)".
The member_type for example - (company-payer, government-payer, volunteer, customer, Charitable Organization, Relative-of-customer, Friend-of-customer)

See related issues https://github.com/savoirfairelinux/santropol-feast/issues/139 and https://github.com/savoirfairelinux/santropol-feast/issues/140.

The above is for discussion !

**Comment by lamontfr** [comment]
I suggest closing this issue. See #161 which proposes a better solution.

**Comment by manumilou** [comment]
Agreed
