### ISSUE TITLE
add IDE file to .gitignore

### ISSUE THREAD

**Issue by maximest-pierre** [savoirfairelinux/santropol-feast#86]
Ex. PyCharm and IDEA

**Comment by RignonNoel** [comment]
Add files of your editor in .gitignore is not a good practice because you can have an infinite and it is not connected to the project itself but to your working method.

Here you just need to configure your computer in local : https://help.github.com/articles/ignoring-files/#create-a-global-gitignore

**Comment by maximest-pierre** [comment]
My train of thought was more on the line of people that have not configure a global gitignore or do git add *.

**Comment by RignonNoel** [comment]
You can't do better than their learning to develop in community...
But i understand your main of thought.

**Comment by maximest-pierre** [comment]
can we close it or keep it open.

**Comment by RignonNoel** [comment]
For me we can close.
